### ISSUE TITLE
Status of server project?

### ISSUE THREAD

**Issue by diizzyy** [picotorrent/server#17]
Hi,

I tried building the server using the feature/pika branch but ran into some issues as the it appears to a bit Windows-centric, is that intended?

I'd be happy to provide a few patches to improve compliation on FreeBSD 13.1 and most likely other UNIX based operating systems if that's of interest.

Edit: Unfortunately pika core dumps instantly if you add any kind of switch like -h or -v but starts without

Best regards,
Daniel

**Comment by vktr** [comment]
Hi!

I don't think I've ever tried building the `feature/pika` branch on Windows, so I don't think you can call it Windows-centric 😄 I'm on Ubuntu and doing all development on that.

If all you want to do is run Pika, there are Docker images published for each push to the `feature/pika` branch, you can find the latest here - https://github.com/picotorrent/server/pkgs/container/pika. Building locally shouldn't be a problem either - it's mostly

```
git submodule update --init --recursive
mkdir build && cd build
cmake ..
cmake --build .
```

I'm still debating whether to include a web UI in the base container or not - right now the web UI is in a separate repo and Docker container and you'd need something like docker-compose to orchestrate it all. Here is my docker-compose setup for a seedbox I run,

```
version: '3.8'

services:
  app:
    image: ghcr.io/picotorrent/pika:0.2.4-pullrequest0016.48
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.routers.app.rule=PathPrefix(`/api`)"
      - "traefik.http.services.app.loadbalancer.server.port=1337"
    restart: unless-stopped
    environment:
      PIKA_CONFIG: |
        db = "/data/pika.db"

        [http]
        addr = "0.0.0.0"
    user: "1000:1000"
    volumes:
      - "./data:/data"
      - "/mnt/media:/media"

  web:
    image: ghcr.io/picotorrent/pika-web:0.1.12
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.routers.web.rule=PathPrefix(`/`)"
    restart: unless-stopped

  traefik:
    image: traefik:v2.6
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:1337"
    restart: unless-stopped
    ports:
      - "1337:1337"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
```

Using that, you should be able to access Pika on port 1337. The setup process will be smoother once I finish up everything and create proper documentation, etc 😄
